"""
Script to build the upgraded, fully-grounded PROJECT_PROPOSAL.md
Synchronized with proposal_data.py, build_trimmed_proposal.py, and interactive_showcase.html.
Incorporates all Software Architecture Audit Refactorings (v2.0.0-RELEASE).
"""

import os
from proposal_data import (
    MARKET_INDICATORS,
    PROBLEMS,
    COMPETITOR_COMPARISON,
    DIFFERENTIATION_DIMENSIONS,
    SEVERITY_MODEL,
    TARGET_USERS,
    STAKEHOLDER_MATRIX,
    GROUNDED_VALUE_TAXONOMY,
    UPGRADED_SMART_OBJECTIVES,
    UPGRADED_SCOPE_MATRIX,
    SCENARIO_VALIDATION_DATA,
    MODULE_SUMMARY,
    RETAILSYNC_TESTING_STRATEGY,
    RETAILSYNC_EDGE_IOT_EXPANSION
)

def generate_markdown():
    lines = []
    
    # Title & Metadata
    lines.append("# RetailSync: Centralized Super Shop Warehouse Management System")
    lines.append("## Capstone Project Proposal — Part 1: Project Planning & Definition")
    lines.append("")
    lines.append("**Course:** SE-231 (Software System Analysis & Design / Capstone Project 2)  ")
    lines.append("**Department:** Department of Software Engineering, Faculty of Science and Information Technology  ")
    lines.append("**Project Team Members:** **Raisul Islam Likhon** (Lead: `251-35-508`), **Shottobroto Dey** (`251-35-017`), **Golam Husnain Papon** (`251-35-529`) | Section: **SWE-44D**  ")
    lines.append("**Submission Term:** Fall 2026 | September 2026 | Version: 2.0.0-RELEASE (AI & Concurrency Upgraded)  ")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Executive Summary
    lines.append("## Executive Summary & Project Abstract")
    lines.append("")
    lines.append("In modern supermarket chains across Bangladesh—such as Shwapno, Agora, Meena Bazar, and Unimart—inventory management is frequently split between two disconnected operational worlds: the front-of-house checkout registers and the back-of-house distribution warehouses. When a customer purchases a carton of milk or a bottle of edible oil at the billing counter, that transaction is recorded in a siloed Point of Sale (POS) database. Back-office warehouse staff often only discover stock depletion hours or even days later through delayed manual tallies or periodic spreadsheets. This structural disconnect leads directly to severe operational losses: perishable goods expire unseen on rear shelves, unrecorded breakages cause 'phantom inventory', and popular grocery staples run out during evening and festival rushes.")
    lines.append("")
    lines.append("RetailSync was designed to solve this exact industry challenge. It is a centralized, high-performance Warehouse Management System (WMS) engineered specifically for the fast-paced grocery retail sector in Bangladesh. The system unifies central distribution warehouses and frontline checkout counters into a single, real-time relational core. By enforcing strict Third Normal Form (3NF) database constraints, non-blocking row-level locking (`SELECT ... FOR UPDATE SKIP LOCKED`) on checkout deductions, directed spatial putaway, automated First-Expired, First-Out (FEFO) batch rotation, and machine-learning demand forecasting (CatBoost with native festival calendar awareness), RetailSync directly tackles the three largest profit leaks in supermarket operations: (1) perishable food spoilage (15% to 22% annual loss), (2) unrecorded inventory shrinkage (1.8% to 2.4% write-offs), and (3) peak-hour stockouts during festival surges (7.5% to 11.2% lost sales).")
    lines.append("")
    lines.append("From an engineering perspective, RetailSync is implemented as a 4-tier cyber-physical architecture combining a Next.js 14 Progressive Web Application (PWA), an asynchronous Python 3.11+ FastAPI backend, a normalized PostgreSQL 16 relational ledger, and an in-memory Redis 7 caching tier. Rather than demanding expensive industrial scanning hardware (such as 60,000 BDT Zebra terminals), RetailSync runs seamlessly on standard 12,000 BDT consumer Android smartphones paired with 3,800 BDT Bluetooth barcode trigger grips, reducing frontline hardware deployment costs by nearly 90%.")
    lines.append("")
    lines.append("> **Core Capstone Thesis & Quantifiable SLO Targets:**  ")
    lines.append("> * **Primary Research Question:** How can centralized relational concurrency, machine-learning demand forecasting, and automated FEFO prioritization eliminate retail stockouts and perishable spoilage in high-density grocery operations?  ")
    lines.append("> * **Key Engineering SLO Target:** Sub-2.0s POS checkout deduction latency (p95 ≤ 800ms) across 10 concurrent branch registers with zero deadlocks and exactly zero overselling.  ")
    lines.append("> * **Methodology:** 14-Week Agile Scrum Lifecycle delivering an incremental, Dockerized production-grade MVP across 6 sprints, validated against 4 stress-injected supermarket scenarios.  ")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Document Architecture
    lines.append("## Document Architecture & Table of Contents")
    lines.append("")
    lines.append("| Section | Title | Summary Scope |")
    lines.append("| :--- | :--- | :--- |")
    lines.append("| **Section 1** | Industry Background & Problem Statement | Operational context, profit leaks, grounded value taxonomy, and problem-to-feature mapping |")
    lines.append("| **Section 2** | Project Objectives & Scope Boundaries | Quantitative SMART objectives (O-01 to O-05) and 4-quadrant defense-proof scope boundaries |")
    lines.append("| **Section 3** | Target Personas & Operational Workflows | User profiles (Manager, Cashier, Operator, Procurement) and end-to-end floor journeys |")
    lines.append("| **Section 4** | Core Functional Modules & AI Forecasting Engine | 11 core modules: Inbound, Putaway, FEFO, POS Concurrency, CatBoost Demand Forecasting DSS, and Shrinkage Audit |")
    lines.append("| **Section 5** | Non-Functional Requirements & Performance SLOs | Latency, throughput, ACID concurrency, security, and food safety regulatory compliance |")
    lines.append("| **Section 6** | System Architecture & Technical Design | 4-tier architecture, operational flow, CatBoost ML pipeline, ER schema, non-blocking locking, idempotency, and quarantine state machine |")
    lines.append("| **Section 7** | Curated Technology Stack & Hardware Strategy | Next.js 14 PWA, FastAPI, PostgreSQL 16, Redis 7, CatBoost, and frugal barcode scanner model |")
    lines.append("| **Section 8** | Development Methodology: Agile Scrum Framework | 14-week sprint roadmap, milestone Gantt, 4 stress-injected validation scenarios, and Definition of Done |")
    lines.append("| **Section 9** | Resource Allocation, Budget & Risk Management | RACI governance matrix, hardware expenditure (< 35,000 BDT), and local operational risk mitigations |")
    lines.append("| **Section 10** | Verification, ROI Impact & Academic Conclusion | Multi-tier testing strategy, full CapEx breakdown & payback period (2.80 months), and academic literature citations |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 1
    lines.append("## 1. Industry Background & Problem Statement")
    lines.append("")
    lines.append("### 1.1 The Modern Grocery Retail Landscape in Bangladesh")
    lines.append("The supermarket and organized grocery retail sector in Bangladesh is expanding rapidly. Driven by rapid urbanization (approximately 65.2 million urban citizens, representing 39.7% of the total population according to BBS Census 2022), rising disposable incomes, and dual-earner households, consumers in metropolitan centers like Dhaka and Chattogram increasingly rely on super shops for their daily groceries. Well-known chains such as Shwapno (operating over 450 outlets), Agora, Meena Bazar, Unimart, and Daily Shopping handle tens of thousands of fast-moving consumer goods (FMCG) and fresh produce items daily.")
    lines.append("")
    lines.append("However, behind the clean checkout counters and barcode scanners of modern storefronts lies a fragile back-office supply chain. While checkout billing has modernized, warehouse stock management, pallet putaway, batch rotation, and store replenishment remain reliant on manual paper manifests, clipboard logs, and fragmented Excel sheets. When a supplier truck delivers 200 cartons of milk to a central warehouse in Tejgaon, workers often check items against a paper purchase order, hand-write batch numbers, and store pallets in whatever aisle has open space. Because there is no real-time synchronization with retail POS terminals, stock data quickly drifts out of sync.")
    lines.append("")
    lines.append("### 1.2 The Three Critical Profit Leaks in Super Shop Operations")
    lines.append("* **1. Perishable Food & Dairy Spoilage (15% to 22%):** Supermarket chains lose between 15% and 22% of perishable food (pasteurized milk, yoghurt, poultry, fresh fruits, and chilled items) annually due to lack of batch-level expiration tracking. When floor staff restock retail shelves, they naturally place incoming pallets at the front because it is physically easier, pushing older batches to the rear where they spoil unnoticed. Selling expired food exposes the supermarket to heavy fines and closure under the Bangladesh Food Safety Act 2013.")
    lines.append("* **2. Phantom Inventory & Operational Shrinkage (1.8% to 2.4%):** An average of 1.8% to 2.4% of total inventory value disappears every year through unrecorded breakages, packaging tears, internal pilferage, and inaccurate delivery counts. Because physical audits occur only once a quarter, the computer system reports items as 'in stock' when the physical shelf is actually empty—a phenomenon known as 'phantom inventory'.")
    lines.append("* **3. Peak-Hour Stockouts & POS Freezing (7.5% to 11.2%):** During high-volume shopping periods—such as the holy month of Ramadan, Eid-ul-Fitr, Shab-e-Barat, and Friday evening rushes—fast-moving staples like edible oil, sugar, and milk sell out in minutes. Because POS checkout counters do not deduct warehouse stock atomically, replenishment alerts lag by hours, leading to empty shelves and an estimated 7.5% to 11.2% in unrealized retail sales from frustrated customer walkouts.")
    lines.append("")
    lines.append("### 1.3 Grounded Value Taxonomy: Epistemological Classification of All Claimed Metrics")
    lines.append("During capstone evaluation and defense, project proposals are often criticized if performance numbers and problem statistics appear arbitrary or unsubstantiated. To establish complete transparency and academic rigor, every figure cited in this proposal is explicitly classified into one of three epistemological categories: (1) Literature & Industry Case Studies published by verified organizations, (2) Empirical Engineering SLOs that will be benchmarked directly through software testing, and (3) Modeled Simulation Assumptions projected for controlled pilot validation:")
    lines.append("")
    lines.append("| Metric / Operational Parameter | Claimed Figure | Epistemological Classification | Empirical Grounding / Academic Source |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for row in GROUNDED_VALUE_TAXONOMY:
        if row[0] == "Metric / Parameter":
            continue
        lines.append(f"| **{row[0]}** | `{row[1]}` | {row[2]} | {row[3]} |")
    lines.append("")
    lines.append("### 1.4 Problem-to-Feature Mapping")
    lines.append("| ID | Real-World Operational Problem | Operational Impact | RetailSync Architectural Solution |")
    lines.append("| :---: | :--- | :--- | :--- |")
    for row in PROBLEMS:
        if row[0] == "ID":
            continue
        lines.append(f"| **{row[0]}** | {row[1]} | {row[2]} | {row[3]} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 2
    lines.append("## 2. Project Objectives & Scope Boundaries")
    lines.append("")
    lines.append("### 2.1 Upgraded SMART Project Objectives")
    lines.append("All project goals are framed with quantifiable metrics, measurement protocols, and sprint milestones:")
    lines.append("")
    lines.append("| ID | Objective Domain | SMART Quantitative Target | Measurement Protocol & Verification Gate | Target Sprint |")
    lines.append("| :---: | :--- | :--- | :--- | :---: |")
    for row in UPGRADED_SMART_OBJECTIVES:
        if row[0] == "ID":
            continue
        lines.append(f"| **{row[0]}** | **{row[1]}** | {row[2]} | {row[3]} | `{row[4]}` |")
    lines.append("")
    lines.append("### 2.2 4-Quadrant Defense-Proof Scope Boundaries")
    lines.append("To prevent project scope creep and defend against examiner critique, RetailSync defines strict operational, technical, and boundary constraints across four quadrants:")
    lines.append("")
    for q_idx, row in enumerate(UPGRADED_SCOPE_MATRIX, start=1):
        lines.append(f"#### Quadrant {q_idx}: {row[0]}")
        lines.append(f"**In-Scope Modules & Features:**\n{row[1]}\n")
        lines.append(f"**Pilot & Operational Constraints:**\n{row[2]}\n")
        lines.append(f"**Explicit Out-of-Scope (Deliberately Excluded):**\n{row[3]}\n")
        lines.append("")
    lines.append("---")
    lines.append("")

    # Section 3
    lines.append("## 3. Target Personas & Floor Workflows")
    lines.append("")
    lines.append("| User Persona | Operational Role | Primary Daily Responsibilities & Pain Points | Key RetailSync Capabilities Utilized |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for row in TARGET_USERS:
        if row[0] in ("User Category", "User Persona", "ID"):
            continue
        lines.append(f"| **{row[0]}** | {row[1]} | {row[2]} | {row[3]} |")
    lines.append("")
    lines.append("### End-to-End Operational Lifecycle Workflow")
    lines.append("1. **Inbound Receiving & GRN Verification:** Supplier deliveries are scanned against active digital POs. Expiration dates, lot numbers, and damaged cartons are captured, generating an immutable Goods Receipt Note (GRN) with strict 65% remaining shelf-life gating.")
    lines.append("2. **Directed Spatial Putaway:** The system computes the optimal bin coordinate (Zone-Aisle-Rack-Shelf-Bin) factoring temperature and SKU velocity. The operator scans the destination bin to confirm docking.")
    lines.append("3. **Real-Time POS Inventory Deduction:** At checkout, the POS issues an atomic deduction. The backend executes a non-blocking row lock (`SELECT ... FOR UPDATE SKIP LOCKED`) on the earliest active batch in < 2.0 seconds with zero overselling and zero lock queue deadlocks.")
    lines.append("4. **Strict FEFO Outbound Allocation:** Store requisitions allocate stock strictly from earliest expiring batches. Expired or quarantined lots are mechanically excluded.")
    lines.append("5. **AI Replenishment Trigger:** CatBoost projects upcoming 7-day demand factoring calendar events; when inventory breaches the dynamic ROP, an automated draft PO is generated.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 4
    lines.append("## 4. Core Functional Modules & AI Demand Forecasting Engine")
    lines.append("")
    lines.append("RetailSync is structured into 11 discrete, cohesive modules operating over a unified relational core:")
    lines.append("")
    lines.append("| Module ID & Name | Requirement Range | Core Functional Capabilities Covered | MoSCoW Priority |")
    lines.append("| :--- | :---: | :--- | :---: |")
    for row in MODULE_SUMMARY:
        if row[0] in ("Module ID & Name", "ID"):
            continue
        lines.append(f"| **{row[0]}** | `{row[1]}` | {row[2]} | **{row[3]}** |")
    lines.append("")
    lines.append("### Detailed Spotlight: Module M-07 (AI Demand Forecasting & Dynamic Replenishment DSS)")
    lines.append("Traditional inventory software relies on static reorder points ($ROP = d \\times L$) that fail catastrophically during supermarket demand swings. RetailSync deploys an AI Demand Forecasting worker paired with Greasley's dynamic safety stock formulation:")
    lines.append("")
    lines.append("1. **Machine Learning Model:** Multi-horizon CatBoost regressor trained on store-level historical POS transactions. CatBoost was explicitly selected over LightGBM for the MVP because of its native handling of categorical features (festival flags, day-of-week, temperature class) without requiring manual one-hot encoding or introducing target leakage. LightGBM is formally deferred to the post-capstone v2.0 roadmap.")
    lines.append("2. **Feature Engineering Pipeline:**")
    lines.append("   * **Temporal Lags:** $t-1, t-7, t-14, t-30$ sales quantities.")
    lines.append("   * **Rolling Statistics:** 7-day and 28-day exponential moving averages (EMA) and standard deviations.")
    lines.append("   * **Festival Calendar Embeddings:** Binary flags and proximity distance vectors for Ramadan (Iftar/Sehri velocity spikes), Eid-ul-Fitr, Eid-ul-Adha, Shab-e-Barat, and Durga Puja.")
    lines.append("   * **Payday Cycle Indicators:** Cyclical day-of-month indicators capturing salary disbursement consumption spikes (1st to 7th of each month).")
    lines.append("3. **Greasley Statistical Safety Stock Formula:**")
    lines.append("   $$SS = Z \\times \\sqrt{(\\overline{L} \\times \\sigma_d^2) + (\\hat{d}_{i,t}^2 \\times \\sigma_L^2)}$$")
    lines.append("   Where:")
    lines.append("   * $Z$ is the service level factor (e.g., $Z=1.65$ for 95%, $Z=2.33$ for 99%).")
    lines.append("   * $\\overline{L}$ is the mean supplier lead time in days.")
    lines.append("   * $\\sigma_d$ is the standard deviation of daily sales.")
    lines.append("   * $\\hat{d}_{i,t}$ is the **AI-forecasted daily demand** for SKU $i$ at horizon $t$.")
    lines.append("   * $\\sigma_L$ is the standard deviation of supplier delivery lead time.")
    lines.append("4. **Dynamic Reorder Point (ROP):**")
    lines.append("   $$ROP = (\\hat{d}_{i,t} \\times \\overline{L}) + SS$$")
    lines.append("5. **Economic Order Quantity (EOQ):**")
    lines.append("   $$EOQ = \\sqrt{\\frac{2 \\times AnnualDemand \\times S}{H}}$$")
    lines.append("")
    lines.append("### Detailed Spotlight: Module M-09 (Cycle Counting & Shrinkage Audit)")
    lines.append("To maintain a feasible 14-week delivery scope while delivering rigorous audit defense, Module M-09 implements an empirical **rule-based threshold alert engine** for the MVP. During blind physical counts, if the absolute discrepancy variance exceeds 3% ($|Actual - Expected| / Expected > 0.03$), the system mechanically generates a high-priority supervisor audit exception, freezes batch putaway, and requires dual-credential authorization before adjustment. Complex unsupervised anomaly detection (Isolation Forest) is deferred to the v2.0 roadmap once multi-month historical variance labels are accumulated.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 5
    lines.append("## 5. Non-Functional Requirements & Performance SLOs")
    lines.append("")
    lines.append("| ID | Category | Specific Metric & SLO Target | Verification Method |")
    lines.append("| :---: | :--- | :--- | :--- |")
    lines.append("| **NFR-01** | Scan Latency | Barcode decode to visual confirmation ≤ 350 ms. | Automated mobile browser profiler with Bluetooth HID trigger. |")
    lines.append("| **NFR-02** | POS Sync Latency | Deduction transaction completes in ≤ 2.0s (p95 ≤ 800ms, p99 ≤ 1.5s). | Locust stress test simulating 10 concurrent registers. |")
    lines.append("| **NFR-03** | Concurrency Isolation | Handle ≥ 50 concurrent floor scanners and 10 POS cash registers with zero deadlocks. | Multi-threaded test runner executing concurrent checkout deductions (`SKIP LOCKED`). |")
    lines.append("| **NFR-04** | Data Integrity | Complete ACID transaction compliance; zero negative stock balances (`CHECK current_quantity >= 0`). | Automated race condition test asserting stock balance constraints. |")
    lines.append("| **NFR-05** | Availability | 99.8% operational uptime during business hours (06:00 to 23:00 BST). | Automated health-check monitoring via Prometheus and Uptime Kuma. |")
    lines.append("| **NFR-06** | Disaster Recovery | Point-In-Time Recovery (PITR) with RPO ≤ 1 min, RTO ≤ 15 min. | Automated database backup verification and WAL restore drills. |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 6
    lines.append("## 6. System Architecture & Technical Design")
    lines.append("")
    lines.append("### 6.1 4-Tier Cyber-Physical Architecture")
    lines.append("RetailSync is structured across four distinct cyber-physical layers, ensuring decoupling, horizontal scalability, and high fault tolerance:")
    lines.append("")
    lines.append("![Figure 1: RetailSync 4-Tier Cyber-Physical System Architecture](assets/figure1_system_architecture.png)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph TB")
    lines.append("    subgraph Tier1 [Tier 1: Client & Scanning Edge]")
    append_t1 = [
        '        PWA["Next.js 14 PWA (Floor Staff)"]',
        '        POS["Branch POS Cash Registers (10 Lanes)"]',
        '        MOB["Android Smartphone + BT Trigger (<4k BDT)"]',
        '        IDB[("Client IndexedDB (Offline Buffer)")]'
    ]
    lines.extend(append_t1)
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph Tier2 [Tier 2: Edge Gateway & Security]")
    append_t2 = [
        '        NGINX["NGINX Reverse Proxy (TLS 1.3 / Rate Limiting)"]',
        '        JWT["Stateless JWT Bearer Token Auth"]'
    ]
    lines.extend(append_t2)
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph Tier3 [Tier 3: Core Application & AI Services]")
    append_t3 = [
        '        API["FastAPI ASGI Async Core Engine"]',
        '        FEFO["FEFO Batch & Expiry Allocation Engine"]',
        '        POS_SVC["Atomic POS Row-Locking Concurrency Engine"]',
        '        AI_WORKER["Celery Worker: CatBoost Forecaster & Quarantine Sweep"]',
        '        DSS["Greasley Statistical Safety Stock & Dynamic ROP"]'
    ]
    lines.extend(append_t3)
    lines.append("    end")
    lines.append("")
    lines.append("    subgraph Tier4 [Tier 4: Enterprise Persistence & Cache]")
    append_t4 = [
        '        PG16[("PostgreSQL 16: 3NF Relational Ledger")]',
        '        REDIS[("Redis 7: Client Idempotency Keys & Session Cache")]'
    ]
    lines.extend(append_t4)
    lines.append("    end")
    lines.append("")
    lines.append("    MOB --> PWA")
    lines.append("    PWA --> IDB")
    lines.append("    PWA --> NGINX")
    lines.append("    POS --> NGINX")
    lines.append("    NGINX --> JWT")
    lines.append("    JWT --> API")
    lines.append("    API --> FEFO")
    lines.append("    API --> POS_SVC")
    lines.append("    API --> AI_WORKER")
    lines.append("    AI_WORKER --> DSS")
    lines.append("    POS_SVC --> PG16")
    lines.append("    API --> PG16")
    lines.append("    API --> REDIS")
    lines.append("```")
    lines.append("")
    lines.append("### 6.2 End-to-End Operational Lifecycle & Process Data Flow")
    lines.append("The end-to-end physical journey of super shop goods—from supplier delivery to POS sales and cycle audits:")
    lines.append("")
    lines.append("![Figure 2: End-to-End Operational Lifecycle & Process Data Flow](assets/figure2_operational_flow.png)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("flowchart LR")
    lines.append('    A["1. Supplier Delivery"] --> B["2. Inbound Receiving & GRN"]')
    lines.append('    B --> C["3. Directed Putaway (ABC Zones)"]')
    lines.append('    C --> D["4. FEFO Batch Ledger"]')
    lines.append('    D --> E["5. Store Wave Picking"]')
    lines.append('    E --> F["6. POS Atomic Sales (Sub-2s)"]')
    lines.append('    F --> G["7. Continuous Cycle Audit"]')
    lines.append('    G -. Discrepancy Reconciliation .-> D')
    lines.append('    F -. Real-Time Velocity .-> H["AI Replenishment DSS"]')
    lines.append('    H -. Automated Draft PO .-> A')
    lines.append("```")
    lines.append("")
    lines.append("### 6.3 AI Demand Forecasting & Replenishment Pipeline")
    lines.append("Detailed flow of historical sales ingestion, feature transformation, model inference, and dynamic inventory parameterization:")
    lines.append("")
    lines.append("![Figure 3: AI Demand Forecasting & Predictive Replenishment ML Pipeline](assets/figure3_ai_forecasting_pipeline.png)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("flowchart TD")
    lines.append('    POS_HIST[("Historical POS Sales Ledger")] --> FEAT["Feature Engineering (Lags, EMA, Calendar Flags)"]')
    lines.append('    CAL["Festival Embeddings (Ramadan, Eid, Salary Cycles)"] --> FEAT')
    lines.append('    FEAT --> MODEL["CatBoost Regressor Engine (Native Categorical Embeddings)"]')
    lines.append('    MODEL --> PREDICT["Predicted Daily Demand d_hat (WAPE < 14.5%)"]')
    lines.append('    PREDICT --> GREASLEY["Greasley Formula: SS = Z * sqrt(L*sigma_d^2 + d_hat^2*sigma_L^2)"]')
    lines.append('    GREASLEY --> ROP["Dynamic Reorder Point: ROP = d_hat * L + SS"]')
    lines.append('    ROP --> AUTO_PO["Automated Draft Purchase Order Generation"]')
    lines.append("```")
    lines.append("")
    lines.append("### 6.4 Relational Database Schema & Entity Relationship Architecture")
    lines.append("RetailSync enforces strict Third Normal Form (3NF) across all inventory transactions. The core relational schema guarantees complete double-entry traceability, referential integrity, and negative-stock prevention at the database engine level:")
    lines.append("")
    lines.append("```mermaid")
    lines.append("erDiagram")
    lines.append("    PRODUCTS ||--o{ PRODUCT_BATCHES : contains")
    lines.append("    SUPPLIERS ||--o{ PRODUCT_BATCHES : supplies")
    lines.append("    WAREHOUSE_BINS ||--o{ PRODUCT_BATCHES : stores")
    lines.append("    PRODUCT_BATCHES ||--o{ STOCK_MOVEMENTS : tracks")
    lines.append("    USERS ||--o{ STOCK_MOVEMENTS : authorizes")
    lines.append("    USERS ||--o{ AUDIT_LOG : generates")
    lines.append("")
    lines.append("    PRODUCTS {")
    lines.append("        int product_id PK")
    lines.append("        string sku UK")
    lines.append("        string name")
    lines.append("        string category")
    lines.append("        string temperature_req")
    lines.append("        int shelf_life_days")
    lines.append("        timestamptz created_at")
    lines.append("    }")
    lines.append("    PRODUCT_BATCHES {")
    lines.append("        int batch_id PK")
    lines.append("        int product_id FK")
    lines.append("        int supplier_id FK")
    lines.append("        string lot_number")
    lines.append("        int received_qty")
    lines.append('        int current_quantity "CHECK >= 0"')
    lines.append("        date expiry_date")
    lines.append("        string quarantine_status")
    lines.append("        int bin_id FK")
    lines.append("        timestamptz created_at")
    lines.append("        timestamptz updated_at")
    lines.append("    }")
    lines.append("    STOCK_MOVEMENTS {")
    lines.append("        bigint movement_id PK")
    lines.append("        int batch_id FK")
    lines.append("        string movement_type")
    lines.append("        int quantity_delta")
    lines.append("        string reference_id")
    lines.append("        string source")
    lines.append("        timestamptz created_at")
    lines.append("    }")
    lines.append("    WAREHOUSE_BINS {")
    lines.append("        int bin_id PK")
    lines.append("        string bin_code UK")
    lines.append("        string zone")
    lines.append("        string aisle")
    lines.append("        string rack")
    lines.append("        string shelf")
    lines.append("        int max_capacity")
    lines.append("        int current_occupancy")
    lines.append("    }")
    lines.append("    USERS {")
    lines.append("        int user_id PK")
    lines.append("        string username UK")
    lines.append("        string email UK")
    lines.append("        string password_hash")
    lines.append("        string role")
    lines.append("        boolean is_active")
    lines.append("    }")
    lines.append("    AUDIT_LOG {")
    lines.append("        bigint log_id PK")
    lines.append("        int user_id FK")
    lines.append("        string action")
    lines.append("        string entity_type")
    lines.append("        string entity_id")
    lines.append("        jsonb payload")
    lines.append("        timestamptz created_at")
    lines.append("    }")
    lines.append("```")
    lines.append("")
    lines.append("### 6.5 High-Throughput Concurrency Control: Non-Blocking Row-Level Locking")
    lines.append("To prevent overselling and race conditions when multiple cash registers ring up the same SKU during peak shopping surges, RetailSync employs non-blocking pessimistic row locking (`SKIP LOCKED`):")
    lines.append("")
    lines.append("```sql")
    lines.append("-- Optimized: non-blocking FEFO batch acquisition")
    lines.append("SELECT batch_id, current_quantity, expiry_date ")
    lines.append("FROM product_batches ")
    lines.append("WHERE product_id = :p_id ")
    lines.append("  AND current_quantity >= :quantity ")
    lines.append("  AND quarantine_status = 'AVAILABLE' ")
    lines.append("ORDER BY expiry_date ASC ")
    lines.append("LIMIT 1 ")
    lines.append("FOR UPDATE SKIP LOCKED;")
    lines.append("```")
    lines.append("")
    lines.append("The `SKIP LOCKED` clause is a critical architectural requirement. In standard `FOR UPDATE` queries, concurrent transactions queue behind locked rows, compounding latency and creating lock queue deadlocks during checkout spikes. With `SKIP LOCKED`, concurrent requests immediately bypass already-locked rows and attempt acquisition on the next valid batch. In low-stock scenarios (such as Scenario B where 10 cashiers compete for the final 5 units), the first 5 transactions lock and deduct, while competing requests immediately observe zero unlocked stock and return an instantaneous 'Out of Stock' status (p95 ≤ 800ms) with zero deadlocks.")
    lines.append("")
    lines.append("### 6.6 Client-Side Idempotency Key Architecture for Offline Resilience")
    lines.append("To guarantee exactly-once execution during intermittent warehouse broadband blackouts, RetailSync requires **client-generated idempotency keys** (`X-Idempotency-Key`).")
    lines.append("")
    lines.append("* **Key Format:** `{device_id}-{epoch_ms}-{local_sequence}` (e.g., `POS01-1790584900123-00042`).")
    lines.append("* **Generation Lifecycle:** The key is generated inside the PWA client at the exact instant the transaction is created—not at synchronization time. This guarantees the transaction retains an immutable identity during the offline window.")
    lines.append("* **Storage & Replay:** Queued transactions are encrypted in IndexedDB. Upon network recovery, bulk synchronization submits each payload with its original header. Redis verifies: `SET idempotency:{key} {tx_id} NX EX 86400`. If the key exists, Redis immediately returns the cached transaction response without re-executing inventory deductions, permanently eliminating duplicate debits.")
    lines.append("")
    lines.append("### 6.7 Batch Lifecycle & Food Safety Quarantine State Machine")
    lines.append("RetailSync models the lifecycle of every food and grocery batch through six deterministic states governed by database CHECK constraints and automated background workers:")
    lines.append("")
    lines.append("```mermaid")
    lines.append("stateDiagram-v2")
    lines.append("    [*] --> PENDING_RECEIPT: Supplier Delivery Docked")
    lines.append("    PENDING_RECEIPT --> AVAILABLE: Digital GRN & Barcode Verified (Shelf Life >= 65%)")
    lines.append("    PENDING_RECEIPT --> QUARANTINED: Quality Gate Rejection (Shelf Life < 65% / Damage)")
    lines.append("    AVAILABLE --> NEAR_EXPIRY: Celery Daily Sweep at 02:00 BST (Expiry <= 3 Days)")
    lines.append("    NEAR_EXPIRY --> AVAILABLE: Supervisor Inspection Override")
    lines.append("    NEAR_EXPIRY --> QUARANTINED: Expiry Date Reached (Expiry <= 0 Days)")
    lines.append("    AVAILABLE --> QUARANTINED: Floor Damage Logged in Cycle Count")
    lines.append("    QUARANTINED --> WRITTEN_OFF: Supervisor Write-Off Approved")
    lines.append("    AVAILABLE --> DEPLETED: POS / Wave Pick Deductions (Current Qty = 0)")
    lines.append("    DEPLETED --> [*]")
    lines.append("    WRITTEN_OFF --> [*]")
    lines.append("```")
    lines.append("")
    lines.append("State transitions are enforced through Celery beat tasks scheduled daily at 02:00 BST. Any batch with $\\le$ 3 days remaining shelf-life is automatically transitioned to `NEAR_EXPIRY` and flagged for markdown. Batches reaching expiration date are immediately locked to `QUARANTINED`, mechanically preventing pick-list generation and eliminating Bangladesh Food Safety Act violations.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 7
    lines.append("## 7. Curated Technology Stack & Hardware Strategy")
    lines.append("")
    lines.append("| Component | Technology | Version | Engineering Justification |")
    lines.append("| :--- | :--- | :---: | :--- |")
    lines.append("| **Frontend PWA** | Next.js / React | `14.2+` | Single Page Application (SPA) speed with server-side rendering (SSR) for dashboards; eliminates page-reload latency on mobile scanning terminals. |")
    lines.append("| **Backend API** | FastAPI / Python | `3.11+` | Asynchronous ASGI framework with native async/await event loop, sub-millisecond route execution, and automatic OpenAPI schema generation. |")
    lines.append("| **AI / ML Forecaster** | CatBoost | `1.2+` | Gradient boosting regressor chosen for native categorical handling of festival calendar flags without preprocessing overhead; LightGBM deferred to roadmap. |")
    lines.append("| **Database Core** | PostgreSQL | `16+` | ACID-compliant relational core with non-blocking row-level locking (`SELECT ... FOR UPDATE SKIP LOCKED`), partial indexes, and JSONB audit logs. |")
    lines.append("| **In-Memory Cache** | Redis | `7.2+` | Sub-millisecond distributed cache for session management, rate-limiting tokens, and client idempotency key locks (`X-Idempotency-Key`). |")
    lines.append("| **Barcode Scanner** | Html5-QRCode / ZXing | Latest | Pure JavaScript barcode engine reading 1D (EAN-13, Code 128) and 2D (QR) barcodes directly from smartphone cameras and Bluetooth trigger guns. |")
    lines.append("")
    lines.append("### Frugal Barcode Hardware Strategy")
    lines.append("Traditional industrial terminals (Zebra TC52) cost upwards of 60,000 BDT. RetailSync runs on standard consumer Android smartphones (10,000–12,000 BDT) paired with ergonomic Bluetooth barcode trigger grips (< 4,000 BDT), cutting hardware costs by 90% while achieving sub-350ms scan speeds. Custom IoT firmware development (ESP32/MQTT) is deliberately excluded from scope to preserve delivery focus.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 8
    lines.append("## 8. Development Methodology: Agile Scrum Framework")
    lines.append("")
    lines.append("### 8.1 Methodology Rationale: Why Agile Scrum Over Waterfall?")
    lines.append("RetailSync is developed strictly following the **Agile Scrum Framework**. Sequential methodologies (Waterfall, V-Model) are deliberately rejected due to the dynamic operational realities of modern retail grocery environments:")
    lines.append("* **The Failure of Waterfall in Supermarkets:** Sequential models assume static, unchanging requirements over a 6-month lifecycle. In reality, Bangladeshi supermarket operations experience frequent shifts in supplier terms, festival volume surges (Eid/Ramadan), and unexpected broadband dropouts. Deferring integration and stress testing to Month 4 results in catastrophic concurrency deadlocks and race conditions discovered only on launch day.")
    lines.append("* **The Agile Scrum Advantage:** Scrum provides **empirical process control** through transparent, time-boxed 2-week iterations. Delivering a potentially shippable increment every 14 days allows supermarket supervisors, floor operators, and DIU academic evaluators to test real scanning speeds, mobile UX ergonomics, and database concurrency on physical hardware throughout the project lifecycle.")
    lines.append("")
    lines.append("### 8.2 14-Week Capstone Engineering Roadmap & Milestone Gantt Schedule")
    lines.append("The 14-week engineering lifecycle is structured across six 2-week development sprints plus a 2-week final hardening phase (Total: 137 Story Points):")
    lines.append("")
    lines.append("![Figure 4: 14-Week Capstone Engineering Roadmap & Scenario Gantt Schedule](assets/figure4_gantt_roadmap.png)")
    lines.append("")
    lines.append("```mermaid")
    lines.append("gantt")
    lines.append("    title 14-Week Capstone Engineering Sprint Roadmap")
    lines.append("    dateFormat  YYYY-MM-DD")
    lines.append("    section Sprints")
    lines.append("    Sprint 1: Schema & Auth (21 pts)       :done, s1, 2026-10-01, 14d")
    lines.append("    Sprint 2: Inbound & GRN (24 pts)       :active, s2, after s1, 14d")
    lines.append("    Sprint 3: Putaway & FEFO (26 pts)      :s3, after s2, 14d")
    lines.append("    Sprint 4: POS Concurrency (22 pts)     :s4, after s3, 14d")
    lines.append("    Sprint 5: CatBoost DSS & Picking (23 pts) :s5, after s4, 14d")
    lines.append("    Sprint 6: Audit & Load Test (21 pts)   :s6, after s5, 14d")
    lines.append("    Hardening & Defense Pilot (0 pts)      :s7, after s6, 14d")
    lines.append("    section Validation Scenarios")
    lines.append("    Scenario A: Dock Quality Gate          :crit, milestone, after s2, 0d")
    lines.append("    Scenario B: POS Concurrency Rush       :crit, milestone, after s4, 0d")
    lines.append("    Scenario C: Network Blackout & Sync    :crit, milestone, after s4, 0d")
    lines.append("    Scenario D: Festival AI Demand Surge   :crit, milestone, after s5, 0d")
    lines.append("```")
    lines.append("")
    lines.append("### 8.3 Empirical Scenario-Based Validation Suite")
    lines.append("To prove system correctness beyond theoretical assertions, the software engineering defense will be demonstrated against four stress-injected supermarket scenarios:")
    lines.append("")
    lines.append("| Scenario ID & Title | Operational Context & Stress Injection Event | System Behavior & Algorithmic Response | Verifiable Pass / Acceptance Criteria | Sprint Alignment |")
    lines.append("| :--- | :--- | :--- | :--- | :---: |")
    for row in SCENARIO_VALIDATION_DATA:
        if row[0] in ("Scenario ID & Title", "ID"):
            continue
        lines.append(f"| **{row[0]}** | {row[1]} | {row[2]} | {row[3]} | `{row[4]}` |")
    lines.append("")
    lines.append("### 8.4 Definition of Done (DoD) & Quality Gates")
    lines.append("A user story or sprint task is declared **DONE** and permitted into the production build only when all six quality gates are satisfied:")
    lines.append("1. **Code Complete & Reviewed:** Code committed to Git with conventional commits, merged via Pull Request with peer review and zero linter warnings.")
    lines.append("2. **Automated Test Coverage:** Pytest unit and integration test suites pass with $\\ge$ 80% line coverage in the CI/CD pipeline.")
    lines.append("3. **Concurrency & ACID Validated:** Locust multi-threaded stress tests confirm zero database deadlocks and zero negative balances under simulated 10-cashier peak traffic (`SKIP LOCKED`).")
    lines.append("4. **OpenAPI Schema Documented:** FastAPI endpoints registered with comprehensive Pydantic request/response schemas and error models in Swagger/OpenAPI.")
    lines.append("5. **Containerized Staging Build:** Multi-stage Docker Compose builds and passes automated health checks (`/healthz` returns HTTP 200).")
    lines.append("6. **Mobile Responsive & Ergonomics:** Handheld PWA interface verified on a 375x667 viewport with Bluetooth trigger barcode scanning decode speed under 350ms.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 9
    lines.append("## 9. Resource Allocation, Budget & Risk Management")
    lines.append("")
    lines.append("### 9.1 Hardware & Operational Budget Breakdown")
    lines.append("* **Android Test Smartphone (Android 13, 4GB RAM):** 12,500 BDT")
    lines.append("* **Bluetooth Barcode Trigger Grips (Qty: 2):** 7,600 BDT")
    lines.append("* **Thermal Label & Receipt Printer (4-inch USB/BT):** 6,500 BDT")
    lines.append("* **EAN-128 Adhesive Labels (3,000 labels):** 1,950 BDT")
    lines.append("* **Cloud Staging VPS Hosting (6 Months):** 5,500 BDT")
    lines.append("* **Total Initial Hardware Expenditure:** **34,050 BDT**")
    lines.append("")
    lines.append("### 9.2 Local Operational Risk Management")
    lines.append("* **Network Outages:** Solved via Service Worker and encrypted IndexedDB client caching with client-generated idempotent replay (`X-Idempotency-Key`).")
    lines.append("* **Database Deadlocks under Surge:** Solved via non-blocking row-level batch locks (`ORDER BY expiry_date ASC LIMIT 1 FOR UPDATE SKIP LOCKED`) and connection pooling.")
    lines.append("* **Worker Resistance to Barcode Scanners:** Solved via low-latency audio beep confirmations and simple high-contrast PWA interface.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Section 10
    lines.append("## 10. Verification, ROI Impact, Academic References & Conclusion")
    lines.append("")
    lines.append("### 10.1 Multi-Tier Verification & Testing Strategy")
    lines.append("| Testing Tier | Target Dimension | Test Scenario & Verification Methodology | Verifiable Pass / Acceptance Criteria |")
    lines.append("| :--- | :--- | :--- | :--- |")
    for row in RETAILSYNC_TESTING_STRATEGY:
        if row[0].startswith("Testing Tier") or row[0] in ("Tier", "ID"):
            continue
        lines.append(f"| **{row[0]}** | {row[1]} | {row[2]} | {row[3]} |")
    lines.append("")
    lines.append("### 10.2 Expected Operational & Financial Impact (ROI)")
    lines.append("")
    lines.append("#### Complete Initial Capital Expenditure (CapEx) Breakdown")
    lines.append("| Cost Category | Amount (BDT) | Description & Justification |")
    lines.append("| :--- | :---: | :--- |")
    lines.append("| **Hardware Terminals & Peripherals** | 34,050 | Android smartphone (12,500), 2x Bluetooth trigger grips (7,600), thermal printer (6,500), adhesive barcode labels (1,950), 6-month staging VPS (5,500). |")
    lines.append("| **Development & Engineering Labour** | 420,000 | 3-member engineering team × 14 weeks × standard software engineering stipend rate (~10,000 BDT/week/member). |")
    lines.append("| **Contingency Reserve (5%)** | 22,700 | Dedicated contingency buffer for hardware replacement, mobile data packs, and peripheral spares during pilot operations. |")
    lines.append("| **Regulatory & Compliance Documentation** | 8,250 | BSTI/BFSA audit documentation, printed pilot manuals, thermal roll refills, and domain/SSL certificates. |")
    lines.append("| **Total Estimated Initial CapEx** | **485,000** | **Total initial capitalization required for 14-week delivery and pilot deployment.** |")
    lines.append("")
    lines.append("#### Financial Payback Period & Working Arithmetic")
    lines.append("$$\\text{Projected Payback Period} = \\frac{\\text{Total Initial CapEx}}{\\text{Monthly Gross Savings} - \\text{Monthly OpEx}} = \\frac{485,000 \\text{ BDT}}{187,200 \\text{ BDT} - 14,000 \\text{ BDT}} = \\frac{485,000}{173,200} \\approx \\mathbf{2.80 \\text{ Months}}$$")
    lines.append("")
    lines.append("* **Projected Gross Monthly Savings (187,200 BDT):**")
    lines.append("  * **Perishable Spoilage Reduction:** Reducing annual waste from 22% down to < 6% on perishable dairy and poultry turnover saves approximately 112,000 BDT/month.")
    lines.append("  * **Phantom Shrinkage Elimination:** Cutting unrecorded loss from 2.4% down to < 0.4% via double-entry stock movement audits saves approximately 45,200 BDT/month.")
    lines.append("  * **Peak-Hour Stockout Recovery:** Recovering lost retail revenue during evening and festival rushes through dynamic Greasley safety stocks recovers approximately 30,000 BDT/month.")
    lines.append("* **Monthly Ongoing OpEx (14,000 BDT):** Staging cloud VPS, thermal label rolls, 4G backup data packs, and routine server maintenance.")
    lines.append("* **Net Monthly Operational Benefit:** $187,200 - 14,000 = 173,200 \\text{ BDT/month}$.")
    lines.append("* **Economic Conclusion:** The entire initial investment of 485,000 BDT is fully recouped within **2.80 months** of operational pilot deployment.")
    lines.append("")
    lines.append("### 10.3 Academic References & Literature")
    lines.append("1. **Bangladesh Supermarket Owners Association (BSOA)** (2024). *Annual Retail Operations and Supply Chain Loss Report*. Dhaka, Bangladesh.")
    lines.append("2. **Food and Agriculture Organization (FAO)** (2022). *Post-Harvest Losses in South Asian Perishable Food Supply Chains*. Rome: United Nations.")
    lines.append("3. **National Retail Federation (NRF) / NRSS** (2023). *National Retail Security Survey: Inventory Shrinkage Benchmarks*.")
    lines.append("4. **IHL Group** (2023). *Retail Out-of-Stocks: Global Losses and Impact of Automated Replenishment*.")
    lines.append("5. **Greasley, A.** (2013). *Operations Management*. 3rd Edition, John Wiley & Sons (Statistical Safety Stock under dual variance).")
    lines.append("6. **Prokhorenkova, L. et al.** (2018). *CatBoost: unbiased boosting with categorical features*. Advances in Neural Information Processing Systems (NeurIPS 31).")
    lines.append("7. **Ke, G. et al.** (2017). *LightGBM: A Highly Efficient Gradient Boosting Decision Tree*. Advances in Neural Information Processing Systems (NeurIPS 30). *(Deferred to v2.0 benchmark roadmap)*.")
    lines.append("")
    lines.append("### 10.4 Conclusion & Roadmap to Part 2")
    lines.append("RetailSync delivers an empirically grounded, technically sophisticated, and economically viable Warehouse Management System engineered for the Bangladeshi retail landscape. The completion of Part 1 (Project Planning and Definition) establishes the definitive architectural foundation for immediate execution in Part 2 (System Design, Prototyping, and Concurrency Validation).")
    lines.append("")

    return "\n".join(lines)

if __name__ == "__main__":
    md_content = generate_markdown()
    target_path = os.path.join(os.path.dirname(__file__), "..", "proposal", "PROJECT_PROPOSAL.md")
    with open(target_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    print(f"Successfully generated upgraded PROJECT_PROPOSAL.md ({len(md_content)} bytes)")
